version: '3.9'
name: 'dox-prod'
networks:
  DoX_net:

services:
  DoX_app:
    image: dox_app-prod
    build:
      context: ../../
      dockerfile: docker/Dockerfile-prod
    command: node server.js

    container_name: DoX_app-prod
    restart: unless-stopped
    ports:
      - "80:8888"
    networks:
      - DoX_net

    depends_on:
      - mongodb
    env_file:
      - ../../.env
    environment:
      - LISTEN_PORT=8888
      - ENDPOINT_URL=http://localhost:8888
      - MAILSERVER_SENDER_ADDRESS=
      - MAILSERVER_HOST=
      - MAILSERVER_PORT=
      - MAILSERVER_PASSWORD=
      - MAILSERVER_USER=
      - MONGODB_URI=mongodb://root:root@DoX_db-prod:27017


  mongodb:
    image: mongo:7.0.0-rc7
    container_name: DoX_db-prod
    restart: unless-stopped
    expose:
      - "27017:27017"
    networks:
      - DoX_net
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: DoX_db